//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlertMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFPOS.Common.AlertMessages", typeof(AlertMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail has been added successfully..
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SFPOS\SFPOSWindows\images\icon\add.png.
        /// </summary>
        public static string AddIcon {
            get {
                return ResourceManager.GetString("AddIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details already exists!.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string btnChangeAdd {
            get {
                return ResourceManager.GetString("btnChangeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string btnChangeUpdate {
            get {
                return ResourceManager.GetString("btnChangeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name should not be left blank!.
        /// </summary>
        public static string CategoryNameValidation {
            get {
                return ResourceManager.GetString("CategoryNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategorySearch {
            get {
                return ResourceManager.GetString("CategorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string ConfirmDeletionAlert {
            get {
                return ResourceManager.GetString("ConfirmDeletionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SFPOS\SFPOSWindows\images\icon\delete.png.
        /// </summary>
        public static string DeleteIcon {
            get {
                return ResourceManager.GetString("DeleteIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail has been deleted successfully..
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select specific value from drop down box .
        /// </summary>
        public static string DropdownValidation {
            get {
                return ResourceManager.GetString("DropdownValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email id should be in correct format.!.
        /// </summary>
        public static string EmailValid1 {
            get {
                return ResourceManager.GetString("EmailValid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email id should be 256 characters.!.
        /// </summary>
        public static string EmailValid2 {
            get {
                return ResourceManager.GetString("EmailValid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId should not be left blank!.
        /// </summary>
        public static string EmailValid3 {
            get {
                return ResourceManager.GetString("EmailValid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name should not be left blank!.
        /// </summary>
        public static string EmpFirstName1 {
            get {
                return ResourceManager.GetString("EmpFirstName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name should be 50 characters!.
        /// </summary>
        public static string EmpFirstName2 {
            get {
                return ResourceManager.GetString("EmpFirstName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name should be 50 characters.!.
        /// </summary>
        public static string EmpLastName1 {
            get {
                return ResourceManager.GetString("EmpLastName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name should not be left blank!.
        /// </summary>
        public static string EmpLastName2 {
            get {
                return ResourceManager.GetString("EmpLastName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name/Last name/Email/Phone.
        /// </summary>
        public static string EmployeeSearch {
            get {
                return ResourceManager.GetString("EmployeeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Should not be left blank!.
        /// </summary>
        public static string EmpPasswordValid1 {
            get {
                return ResourceManager.GetString("EmpPasswordValid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must between 8 to 12 Character.
        /// </summary>
        public static string EmpPasswordValid2 {
            get {
                return ResourceManager.GetString("EmpPasswordValid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must containd one special character,one upper case,one lower case and one number.
        /// </summary>
        public static string EmpPasswordValid3 {
            get {
                return ResourceManager.GetString("EmpPasswordValid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date has passed so you cant change in this!.
        /// </summary>
        public static string EndDatePast {
            get {
                return ResourceManager.GetString("EndDatePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than current date!.
        /// </summary>
        public static string EndDateValid1 {
            get {
                return ResourceManager.GetString("EndDateValid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than start date!.
        /// </summary>
        public static string EndDateValid2 {
            get {
                return ResourceManager.GetString("EndDateValid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax should not be left blank!.
        /// </summary>
        public static string FaxValid {
            get {
                return ResourceManager.GetString("FaxValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Header/Line Order detail has been posted successfully..
        /// </summary>
        public static string HeaderLinepost {
            get {
                return ResourceManager.GetString("HeaderLinepost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationAlert {
            get {
                return ResourceManager.GetString("InformationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line amount exclusive tax should not be left blank!.
        /// </summary>
        public static string LineAmtExclTaxValid {
            get {
                return ResourceManager.GetString("LineAmtExclTaxValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line amount inclusive tax should not be left blank!.
        /// </summary>
        public static string LineAmtInclTaxValid {
            get {
                return ResourceManager.GetString("LineAmtInclTaxValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity should not be left blank!.
        /// </summary>
        public static string LineQuantityValid {
            get {
                return ResourceManager.GetString("LineQuantityValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax amount should not be left blank!.
        /// </summary>
        public static string LineTaxAmtValid {
            get {
                return ResourceManager.GetString("LineTaxAmtValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax should not be left blank!.
        /// </summary>
        public static string LineTaxValid {
            get {
                return ResourceManager.GetString("LineTaxValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit cost should not be left blank!.
        /// </summary>
        public static string LineUnitCostValid {
            get {
                return ResourceManager.GetString("LineUnitCostValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not contains numeric value!.
        /// </summary>
        public static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numaric values!.
        /// </summary>
        public static string OnlyNumberAllow {
            get {
                return ResourceManager.GetString("OnlyNumberAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number should not be left blank..
        /// </summary>
        public static string PhoneNoValid1 {
            get {
                return ResourceManager.GetString("PhoneNoValid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number should not be alphanumeric..
        /// </summary>
        public static string PhoneNoValid2 {
            get {
                return ResourceManager.GetString("PhoneNoValid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.jpg;*.jpeg;.*.gif;*.png)|*.jpg;*.jpeg;.*.gif;*.png.
        /// </summary>
        public static string ProductImageFormat {
            get {
                return ResourceManager.GetString("ProductImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name should not be left blank!.
        /// </summary>
        public static string ProductNameValid {
            get {
                return ResourceManager.GetString("ProductNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price should not be left blank!.
        /// </summary>
        public static string ProductSalePrice {
            get {
                return ResourceManager.GetString("ProductSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sales price should not be left blank!.
        /// </summary>
        public static string ProductSalesDiscValid {
            get {
                return ResourceManager.GetString("ProductSalesDiscValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name/UPC Code.
        /// </summary>
        public static string ProductSearch {
            get {
                return ResourceManager.GetString("ProductSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  should not be left blank!.
        /// </summary>
        public static string ProductUoMDiscriptionValid {
            get {
                return ResourceManager.GetString("ProductUoMDiscriptionValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure  should not be left blank!.
        /// </summary>
        public static string ProductUoMQtyValid {
            get {
                return ResourceManager.GetString("ProductUoMQtyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC code should not be left blank!.
        /// </summary>
        public static string ProductUpcCodeValid1 {
            get {
                return ResourceManager.GetString("ProductUpcCodeValid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC Code should not be alphanumeric..
        /// </summary>
        public static string ProductUpcCodeValid2 {
            get {
                return ResourceManager.GetString("ProductUpcCodeValid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC Code Should be in correct format! Format : xxxxxxxxxxxx.
        /// </summary>
        public static string ProductUpcCodeValid3 {
            get {
                return ResourceManager.GetString("ProductUpcCodeValid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC Code should not be left blank!.
        /// </summary>
        public static string ProductVendorUpcCodeValid {
            get {
                return ResourceManager.GetString("ProductVendorUpcCodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderdate should be greater than today.!.
        /// </summary>
        public static string purchaseOrderOrderDate {
            get {
                return ResourceManager.GetString("purchaseOrderOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name/Invoice No.
        /// </summary>
        public static string PurchaseOrderSearch {
            get {
                return ResourceManager.GetString("PurchaseOrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Invoice No. should not be left blank!.
        /// </summary>
        public static string purchaseOrderVendorInvoiceNo1 {
            get {
                return ResourceManager.GetString("purchaseOrderVendorInvoiceNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Invoice No. already exist.!.
        /// </summary>
        public static string purchaseOrderVendorInvoiceNo2 {
            get {
                return ResourceManager.GetString("purchaseOrderVendorInvoiceNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid invoice no.! Format : xxxxxxxxxx.
        /// </summary>
        public static string purchaseOrderVendorInvoiceNo3 {
            get {
                return ResourceManager.GetString("purchaseOrderVendorInvoiceNo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm permission.
        /// </summary>
        public static string ReloPermissionConfirm {
            get {
                return ResourceManager.GetString("ReloPermissionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to allow.
        /// </summary>
        public static string RolePermissionConfirmAllow {
            get {
                return ResourceManager.GetString("RolePermissionConfirmAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove.
        /// </summary>
        public static string RolePermissionConfirmRemove {
            get {
                return ResourceManager.GetString("RolePermissionConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to &apos;DELETE&apos; the.
        /// </summary>
        public static string RolePermissionDelete {
            get {
                return ResourceManager.GetString("RolePermissionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to &apos;EDIT&apos; the.
        /// </summary>
        public static string RolePermissionEdit {
            get {
                return ResourceManager.GetString("RolePermissionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string RolePermissionInfoAlert {
            get {
                return ResourceManager.GetString("RolePermissionInfoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to &apos;INSERT&apos; the.
        /// </summary>
        public static string RolePermissionInsert {
            get {
                return ResourceManager.GetString("RolePermissionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t push role. \nIt is already present the List.!.
        /// </summary>
        public static string RolePermissionValid {
            get {
                return ResourceManager.GetString("RolePermissionValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to &apos;VIEW&apos; the.
        /// </summary>
        public static string RolePermissionView {
            get {
                return ResourceManager.GetString("RolePermissionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Type.
        /// </summary>
        public static string RoleSearch {
            get {
                return ResourceManager.GetString("RoleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleType should not be left blank!.
        /// </summary>
        public static string RoleTypeValid {
            get {
                return ResourceManager.GetString("RoleTypeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be greater than current date!.
        /// </summary>
        public static string StartDateValid {
            get {
                return ResourceManager.GetString("StartDateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name should not be left blank!.
        /// </summary>
        public static string StoreNameValid {
            get {
                return ResourceManager.GetString("StoreNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name/Address/City.
        /// </summary>
        public static string StoreSearch {
            get {
                return ResourceManager.GetString("StoreSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plase enter zip code in proper format.
        /// </summary>
        public static string StoreZipCodeValid {
            get {
                return ResourceManager.GetString("StoreZipCodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category should not be left blank!.
        /// </summary>
        public static string SubCategoryNameValid {
            get {
                return ResourceManager.GetString("SubCategoryNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category Name.
        /// </summary>
        public static string SubCategorySearch {
            get {
                return ResourceManager.GetString("SubCategorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessAlert {
            get {
                return ResourceManager.GetString("SuccessAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Group Code should not be left blank!.
        /// </summary>
        public static string TaxGroupCodeValid {
            get {
                return ResourceManager.GetString("TaxGroupCodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string TaxGroupSearch {
            get {
                return ResourceManager.GetString("TaxGroupSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Group Code.
        /// </summary>
        public static string TaxrateSearch {
            get {
                return ResourceManager.GetString("TaxrateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax should not be left blank.!.
        /// </summary>
        public static string TaxValid {
            get {
                return ResourceManager.GetString("TaxValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not be left blank!.
        /// </summary>
        public static string UoMCodeValid {
            get {
                return ResourceManager.GetString("UoMCodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoM.
        /// </summary>
        public static string UOMSearch {
            get {
                return ResourceManager.GetString("UOMSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail has been updated successfully..
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor invoice no. must be in numeric format!.
        /// </summary>
        public static string VendorInvoiceNoValid {
            get {
                return ResourceManager.GetString("VendorInvoiceNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name should not be left blank!.
        /// </summary>
        public static string VendorNameValid {
            get {
                return ResourceManager.GetString("VendorNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        public static string VendorSearch {
            get {
                return ResourceManager.GetString("VendorSearch", resourceCulture);
            }
        }
    }
}
