//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataContext : DbContext
    {
        public DataContext(string constr) : base(constr)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_InvoiceMaster> tbl_InvoiceMaster { get; set; }
        public virtual DbSet<tbl_LedgerTypeMaster> tbl_LedgerTypeMaster { get; set; }
        public virtual DbSet<tbl_LoginMaster> tbl_LoginMaster { get; set; }
        public virtual DbSet<tbl_MenuMaster> tbl_MenuMaster { get; set; }
        public virtual DbSet<tbl_PostedPurchaseHeader> tbl_PostedPurchaseHeader { get; set; }
        public virtual DbSet<tbl_PostedPurchaseLine> tbl_PostedPurchaseLine { get; set; }
        public virtual DbSet<tbl_ProductSaleDiscountMaster> tbl_ProductSaleDiscountMaster { get; set; }
        public virtual DbSet<tbl_ProductSalePriceMaster> tbl_ProductSalePriceMaster { get; set; }
        public virtual DbSet<tbl_ProductUoM> tbl_ProductUoM { get; set; }
        public virtual DbSet<tbl_PurchaseHeader> tbl_PurchaseHeader { get; set; }
        public virtual DbSet<tbl_PurchaseLine> tbl_PurchaseLine { get; set; }
        public virtual DbSet<tbl_RolePermission> tbl_RolePermission { get; set; }
        public virtual DbSet<tbl_ShortcutkeyMaster> tbl_ShortcutkeyMaster { get; set; }
        public virtual DbSet<tbl_State> tbl_State { get; set; }
        public virtual DbSet<tbl_TaxGroupMaster> tbl_TaxGroupMaster { get; set; }
        public virtual DbSet<tbl_TaxRateMaster> tbl_TaxRateMaster { get; set; }
        public virtual DbSet<tbl_UnitMeasureMaster> tbl_UnitMeasureMaster { get; set; }
        public virtual DbSet<tbl_SectionMaster> tbl_SectionMaster { get; set; }
        public virtual DbSet<tbl_SettingMaster> tbl_SettingMaster { get; set; }
        public virtual DbSet<tbl_StoreMaster> tbl_StoreMaster { get; set; }
        public virtual DbSet<tbl_TillBalancing> tbl_TillBalancing { get; set; }
        public virtual DbSet<tbl_ExceptionLog> tbl_ExceptionLog { get; set; }
        public virtual DbSet<tbl_ProductVendorMaster> tbl_ProductVendorMaster { get; set; }
        public virtual DbSet<tbl_PriceHistory> tbl_PriceHistory { get; set; }
        public virtual DbSet<tbl_SyncLog> tbl_SyncLog { get; set; }
        public virtual DbSet<tbl_UpdateLog> tbl_UpdateLog { get; set; }
        public virtual DbSet<tbl_ReleaseMaster> tbl_ReleaseMaster { get; set; }
        public virtual DbSet<tbl_LottoTrans> tbl_LottoTrans { get; set; }
        public virtual DbSet<tbl_CustomerAppliedCoupon> tbl_CustomerAppliedCoupon { get; set; }
        public virtual DbSet<tbl_ProductLedger> tbl_ProductLedger { get; set; }
        public virtual DbSet<tbl_DepartmentMaster> tbl_DepartmentMaster { get; set; }
        public virtual DbSet<tbl_CounterMaster> tbl_CounterMaster { get; set; }
        public virtual DbSet<tbl_RoleMaster> tbl_RoleMaster { get; set; }
        public virtual DbSet<tbl_FilterColumns> tbl_FilterColumns { get; set; }
        public virtual DbSet<tbl_CustomerMaster> tbl_CustomerMaster { get; set; }
        public virtual DbSet<tbl_VendorMaster> tbl_VendorMaster { get; set; }
        public virtual DbSet<tbl_TillStatusReport> tbl_TillStatusReport { get; set; }
        public virtual DbSet<tbl_EmployeeMaster> tbl_EmployeeMaster { get; set; }
        public virtual DbSet<tbl_ProductMaster> tbl_ProductMaster { get; set; }
        public virtual DbSet<tbl_OrderDetail> tbl_OrderDetail { get; set; }
        public virtual DbSet<tbl_TransSuspenMaster> tbl_TransSuspenMaster { get; set; }
        public virtual DbSet<tbl_OrderEPXLog> tbl_OrderEPXLog { get; set; }
        public virtual DbSet<tbl_PaymentTrans> tbl_PaymentTrans { get; set; }
        public virtual DbSet<tbl_OrderMaster> tbl_OrderMaster { get; set; }
        public virtual DbSet<tbl_CouponAppliedDepartment> tbl_CouponAppliedDepartment { get; set; }
        public virtual DbSet<tbl_CouponMaster> tbl_CouponMaster { get; set; }
    
        public virtual ObjectResult<SP_GetDepartmentReportList_Result> SP_GetDepartmentReportList(Nullable<long> storeid, Nullable<long> departmentid, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var storeidParameter = storeid.HasValue ?
                new ObjectParameter("storeid", storeid) :
                new ObjectParameter("storeid", typeof(long));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("Departmentid", departmentid) :
                new ObjectParameter("Departmentid", typeof(long));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDepartmentReportList_Result>("SP_GetDepartmentReportList", storeidParameter, departmentidParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<SP_GetEmployeeReportList_Result> SP_GetEmployeeReportList(Nullable<long> storeID)
        {
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("storeID", storeID) :
                new ObjectParameter("storeID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmployeeReportList_Result>("SP_GetEmployeeReportList", storeIDParameter);
        }
    
        public virtual ObjectResult<SP_GetProductSaleDiscountList_Result> SP_GetProductSaleDiscountList(Nullable<long> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductSaleDiscountList_Result>("SP_GetProductSaleDiscountList", productIDParameter);
        }
    
        public virtual ObjectResult<SP_GetProductSalePriceList_Result> SP_GetProductSalePriceList(Nullable<long> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductSalePriceList_Result>("SP_GetProductSalePriceList", productIDParameter);
        }
    
        public virtual ObjectResult<SP_GetPurchaseLine_Result> SP_GetPurchaseLine(string uPCCODE_, Nullable<long> purchaseHeaderID_)
        {
            var uPCCODE_Parameter = uPCCODE_ != null ?
                new ObjectParameter("UPCCODE_", uPCCODE_) :
                new ObjectParameter("UPCCODE_", typeof(string));
    
            var purchaseHeaderID_Parameter = purchaseHeaderID_.HasValue ?
                new ObjectParameter("PurchaseHeaderID_", purchaseHeaderID_) :
                new ObjectParameter("PurchaseHeaderID_", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPurchaseLine_Result>("SP_GetPurchaseLine", uPCCODE_Parameter, purchaseHeaderID_Parameter);
        }
    
        public virtual ObjectResult<SP_GetPurchaseOrderList_Result> SP_GetPurchaseOrderList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPurchaseOrderList_Result>("SP_GetPurchaseOrderList");
        }
    
        public virtual ObjectResult<SP_GetReportDayMonthYearSell_Result> SP_GetReportDayMonthYearSell(Nullable<long> storeID, Nullable<int> month, Nullable<int> year)
        {
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(long));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetReportDayMonthYearSell_Result>("SP_GetReportDayMonthYearSell", storeIDParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<SP_GetReportDepartmentWiseSales_Result> SP_GetReportDepartmentWiseSales(Nullable<long> storeID)
        {
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetReportDepartmentWiseSales_Result>("SP_GetReportDepartmentWiseSales", storeIDParameter);
        }
    
        public virtual ObjectResult<SP_GetReportTotalSales_Result> SP_GetReportTotalSales(Nullable<long> storeID)
        {
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetReportTotalSales_Result>("SP_GetReportTotalSales", storeIDParameter);
        }
    
        public virtual ObjectResult<SP_GetSalesPersonList_Result> SP_GetSalesPersonList(Nullable<long> sTOREID, Nullable<long> eMPLOYEEID, Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var eMPLOYEEIDParameter = eMPLOYEEID.HasValue ?
                new ObjectParameter("EMPLOYEEID", eMPLOYEEID) :
                new ObjectParameter("EMPLOYEEID", typeof(long));
    
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSalesPersonList_Result>("SP_GetSalesPersonList", sTOREIDParameter, eMPLOYEEIDParameter, sTARTDATEParameter, eNDDATEParameter);
        }
    
        public virtual ObjectResult<SP_GetSectionReportList_Result> SP_GetSectionReportList(Nullable<long> storeid, Nullable<long> sectionid, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var storeidParameter = storeid.HasValue ?
                new ObjectParameter("storeid", storeid) :
                new ObjectParameter("storeid", typeof(long));
    
            var sectionidParameter = sectionid.HasValue ?
                new ObjectParameter("Sectionid", sectionid) :
                new ObjectParameter("Sectionid", typeof(long));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSectionReportList_Result>("SP_GetSectionReportList", storeidParameter, sectionidParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<SP_GetTaxRateList_Result> SP_GetTaxRateList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTaxRateList_Result>("SP_GetTaxRateList");
        }
    
        public virtual ObjectResult<SP_GetUoMList_Result> SP_GetUoMList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetUoMList_Result>("SP_GetUoMList");
        }
    
        public virtual ObjectResult<SP_GetVendorReportList_Result> SP_GetVendorReportList(Nullable<long> storeId, Nullable<long> vendorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var storeIdParameter = storeId.HasValue ?
                new ObjectParameter("StoreId", storeId) :
                new ObjectParameter("StoreId", typeof(long));
    
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("VendorID", vendorID) :
                new ObjectParameter("VendorID", typeof(long));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetVendorReportList_Result>("SP_GetVendorReportList", storeIdParameter, vendorIDParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<SP_InventoryReport_Result> SP_InventoryReport(string fromDate, string toDate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InventoryReport_Result>("SP_InventoryReport", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_InvoiceDetails_Result> SP_InvoiceDetails(Nullable<long> pONumber)
        {
            var pONumberParameter = pONumber.HasValue ?
                new ObjectParameter("PONumber", pONumber) :
                new ObjectParameter("PONumber", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InvoiceDetails_Result>("SP_InvoiceDetails", pONumberParameter);
        }
    
        public virtual ObjectResult<SP_GetOrderDetailList_Result> SP_GetOrderDetailList(Nullable<long> oRDERID)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetOrderDetailList_Result>("SP_GetOrderDetailList", oRDERIDParameter);
        }
    
        public virtual ObjectResult<SP_GetDataSyncStatus_Result> SP_GetDataSyncStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDataSyncStatus_Result>("SP_GetDataSyncStatus");
        }
    
        public virtual ObjectResult<SP_GetStoreList_Result> SP_GetStoreList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetStoreList_Result>("SP_GetStoreList");
        }
    
        public virtual ObjectResult<SP_Rpt_DepartmentWiseSaleHistory_Result> SP_Rpt_DepartmentWiseSaleHistory(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_DepartmentWiseSaleHistory_Result>("SP_Rpt_DepartmentWiseSaleHistory", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_ProductWiseSaleHistory_Result> SP_Rpt_ProductWiseSaleHistory(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_ProductWiseSaleHistory_Result>("SP_Rpt_ProductWiseSaleHistory", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_SectionWiseSaleHistory_Result> SP_Rpt_SectionWiseSaleHistory(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_SectionWiseSaleHistory_Result>("SP_Rpt_SectionWiseSaleHistory", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_OrderScanner_Result> SP_OrderScanner(string uPCCODE_)
        {
            var uPCCODE_Parameter = uPCCODE_ != null ?
                new ObjectParameter("UPCCODE_", uPCCODE_) :
                new ObjectParameter("UPCCODE_", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OrderScanner_Result>("SP_OrderScanner", uPCCODE_Parameter);
        }
    
        public virtual ObjectResult<SP_GetEmployeeList_Result> SP_GetEmployeeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmployeeList_Result>("SP_GetEmployeeList");
        }
    
        public virtual ObjectResult<SP_GetProductVendorList_Result> SP_GetProductVendorList(Nullable<long> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductVendorList_Result>("SP_GetProductVendorList", productIDParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_TaxReport_Result> SP_Rpt_TaxReport(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_TaxReport_Result>("SP_Rpt_TaxReport", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_GetDisplayLableData_Result> SP_GetDisplayLableData(string uPCCode)
        {
            var uPCCodeParameter = uPCCode != null ?
                new ObjectParameter("UPCCode", uPCCode) :
                new ObjectParameter("UPCCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDisplayLableData_Result>("SP_GetDisplayLableData", uPCCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetProductMovementList_Result> SP_GetProductMovementList(Nullable<long> sTOREID, string uPCCODE, Nullable<int> flag)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var uPCCODEParameter = uPCCODE != null ?
                new ObjectParameter("UPCCODE", uPCCODE) :
                new ObjectParameter("UPCCODE", typeof(string));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductMovementList_Result>("SP_GetProductMovementList", sTOREIDParameter, uPCCODEParameter, flagParameter);
        }
    
        public virtual ObjectResult<SP_GetProductMovementProductDetailList_Result> SP_GetProductMovementProductDetailList(Nullable<long> sTOREID, string uPCCODE, Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var uPCCODEParameter = uPCCODE != null ?
                new ObjectParameter("UPCCODE", uPCCODE) :
                new ObjectParameter("UPCCODE", typeof(string));
    
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductMovementProductDetailList_Result>("SP_GetProductMovementProductDetailList", sTOREIDParameter, uPCCODEParameter, sTARTDATEParameter, eNDDATEParameter);
        }
    
        public virtual ObjectResult<SP_GetProductwiseSalesList_Result> SP_GetProductwiseSalesList(Nullable<long> storeID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<long> departmentID, Nullable<long> sectionID, Nullable<long> venderID, Nullable<int> flag)
        {
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(long));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(long));
    
            var sectionIDParameter = sectionID.HasValue ?
                new ObjectParameter("SectionID", sectionID) :
                new ObjectParameter("SectionID", typeof(long));
    
            var venderIDParameter = venderID.HasValue ?
                new ObjectParameter("VenderID", venderID) :
                new ObjectParameter("VenderID", typeof(long));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductwiseSalesList_Result>("SP_GetProductwiseSalesList", storeIDParameter, startDateParameter, endDateParameter, departmentIDParameter, sectionIDParameter, venderIDParameter, flagParameter);
        }
    
        public virtual ObjectResult<SP_GetReportLastDaysSales_Result> SP_GetReportLastDaysSales(Nullable<long> storeID, Nullable<int> flag)
        {
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(long));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetReportLastDaysSales_Result>("SP_GetReportLastDaysSales", storeIDParameter, flagParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_LottoTotalTrans_Result> SP_Rpt_LottoTotalTrans(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_LottoTotalTrans_Result>("SP_Rpt_LottoTotalTrans", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_GetCouponCustomerVerify_Result> SP_GetCouponCustomerVerify(Nullable<long> cUSTOMERID, Nullable<decimal> amount, Nullable<System.DateTime> dateTime)
        {
            var cUSTOMERIDParameter = cUSTOMERID.HasValue ?
                new ObjectParameter("CUSTOMERID", cUSTOMERID) :
                new ObjectParameter("CUSTOMERID", typeof(long));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCouponCustomerVerify_Result>("SP_GetCouponCustomerVerify", cUSTOMERIDParameter, amountParameter, dateTimeParameter);
        }
    
        public virtual ObjectResult<SP_GetCashierReceipt_Result> SP_GetCashierReceipt(Nullable<long> sTOREID, Nullable<long> cREATEDBY, Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var cREATEDBYParameter = cREATEDBY.HasValue ?
                new ObjectParameter("CREATEDBY", cREATEDBY) :
                new ObjectParameter("CREATEDBY", typeof(long));
    
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCashierReceipt_Result>("SP_GetCashierReceipt", sTOREIDParameter, cREATEDBYParameter, sTARTDATEParameter, eNDDATEParameter);
        }
    
        public virtual ObjectResult<SP_GetOrderMasterList_Result> SP_GetOrderMasterList(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetOrderMasterList_Result>("SP_GetOrderMasterList", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_TillStatusEmployeeWise_Result> SP_TillStatusEmployeeWise(Nullable<long> employeeID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TillStatusEmployeeWise_Result>("SP_TillStatusEmployeeWise", employeeIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_CashierSaleTotal_Result> SP_Rpt_CashierSaleTotal(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_CashierSaleTotal_Result>("SP_Rpt_CashierSaleTotal", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_RegisterSaleTotal_Result> SP_Rpt_RegisterSaleTotal(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_RegisterSaleTotal_Result>("SP_Rpt_RegisterSaleTotal", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_CashierSaleTotalByTrans_Result> SP_Rpt_CashierSaleTotalByTrans(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_CashierSaleTotalByTrans_Result>("SP_Rpt_CashierSaleTotalByTrans", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_RegisterSaleTotalByTrans_Result> SP_Rpt_RegisterSaleTotalByTrans(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_RegisterSaleTotalByTrans_Result>("SP_Rpt_RegisterSaleTotalByTrans", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_GetRoleList_Result> SP_GetRoleList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRoleList_Result>("SP_GetRoleList");
        }
    
        public virtual ObjectResult<SP_GetDepartmentList_Result> SP_GetDepartmentList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDepartmentList_Result>("SP_GetDepartmentList");
        }
    
        public virtual ObjectResult<SP_Rpt_SectionWiseTaxHistory_Result> SP_Rpt_SectionWiseTaxHistory(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_SectionWiseTaxHistory_Result>("SP_Rpt_SectionWiseTaxHistory", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual int SP_GetProductListWithPaging(string searchString, Nullable<int> page)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetProductListWithPaging", searchStringParameter, pageParameter);
        }
    
        public virtual ObjectResult<SP_GetSectionList_Result> SP_GetSectionList(Nullable<long> departmentid)
        {
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("Departmentid", departmentid) :
                new ObjectParameter("Departmentid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSectionList_Result>("SP_GetSectionList", departmentidParameter);
        }
    
        public virtual ObjectResult<SP_GetProductList_With_Paging_Result> SP_GetProductList_With_Paging(string searchString, Nullable<int> page)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductList_With_Paging_Result>("SP_GetProductList_With_Paging", searchStringParameter, pageParameter);
        }
    
        public virtual ObjectResult<SP_TillStatusEmployeeReport_System_Result> SP_TillStatusEmployeeReport_System(Nullable<long> employeeID, Nullable<System.DateTime> date)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(long));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TillStatusEmployeeReport_System_Result>("SP_TillStatusEmployeeReport_System", employeeIDParameter, dateParameter);
        }
    
        public virtual ObjectResult<SP_GetVendorList_Result> SP_GetVendorList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetVendorList_Result>("SP_GetVendorList");
        }
    
        public virtual ObjectResult<SP_TillStatusEmployeeReportsTotal_Result> SP_TillStatusEmployeeReportsTotal(Nullable<long> employeeID, Nullable<System.DateTime> date)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(long));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TillStatusEmployeeReportsTotal_Result>("SP_TillStatusEmployeeReportsTotal", employeeIDParameter, dateParameter);
        }
    
        public virtual int SP_RemoveCounter(string ips)
        {
            var ipsParameter = ips != null ?
                new ObjectParameter("Ips", ips) :
                new ObjectParameter("Ips", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RemoveCounter", ipsParameter);
        }
    
        public virtual ObjectResult<SP_GetCustomerList_Result> SP_GetCustomerList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCustomerList_Result>("SP_GetCustomerList");
        }
    
        public virtual int CRUDOrderMaster(Nullable<int> ordercnt, ObjectParameter identityValue)
        {
            var ordercntParameter = ordercnt.HasValue ?
                new ObjectParameter("ordercnt", ordercnt) :
                new ObjectParameter("ordercnt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRUDOrderMaster", ordercntParameter, identityValue);
        }
    
        public virtual ObjectResult<SP_GetEmployeeList_ByTransDate_Result> SP_GetEmployeeList_ByTransDate(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmployeeList_ByTransDate_Result>("SP_GetEmployeeList_ByTransDate", dateParameter);
        }
    
        public virtual ObjectResult<SP_TillStatusEmployeeReport_Result> SP_TillStatusEmployeeReport(Nullable<long> employeeID, Nullable<System.DateTime> date)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(long));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TillStatusEmployeeReport_Result>("SP_TillStatusEmployeeReport", employeeIDParameter, dateParameter);
        }
    
        public virtual ObjectResult<SP_TillStatusEmployeeReports_Result> SP_TillStatusEmployeeReports(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TillStatusEmployeeReports_Result>("SP_TillStatusEmployeeReports", dateParameter);
        }
    
        public virtual ObjectResult<SP_GetProductList_Result> SP_GetProductList(string searchString, Nullable<bool> isDynamic)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            var isDynamicParameter = isDynamic.HasValue ?
                new ObjectParameter("IsDynamic", isDynamic) :
                new ObjectParameter("IsDynamic", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductList_Result>("SP_GetProductList", searchStringParameter, isDynamicParameter);
        }
    
        public virtual ObjectResult<SP_GetTransSuspendList_Result> SP_GetTransSuspendList(string transSuspendCode)
        {
            var transSuspendCodeParameter = transSuspendCode != null ?
                new ObjectParameter("TransSuspendCode", transSuspendCode) :
                new ObjectParameter("TransSuspendCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTransSuspendList_Result>("SP_GetTransSuspendList", transSuspendCodeParameter);
        }
    
        public virtual ObjectResult<SP_ReciptDetails_Result> SP_ReciptDetails(Nullable<long> orderID, Nullable<long> eMPLOYEEID, Nullable<bool> reprint, string counterIP)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(long));
    
            var eMPLOYEEIDParameter = eMPLOYEEID.HasValue ?
                new ObjectParameter("EMPLOYEEID", eMPLOYEEID) :
                new ObjectParameter("EMPLOYEEID", typeof(long));
    
            var reprintParameter = reprint.HasValue ?
                new ObjectParameter("Reprint", reprint) :
                new ObjectParameter("Reprint", typeof(bool));
    
            var counterIPParameter = counterIP != null ?
                new ObjectParameter("CounterIP", counterIP) :
                new ObjectParameter("CounterIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ReciptDetails_Result>("SP_ReciptDetails", orderIDParameter, eMPLOYEEIDParameter, reprintParameter, counterIPParameter);
        }
    
        public virtual ObjectResult<SP_ScanUPCCode_Result> SP_ScanUPCCode(string uPCCode)
        {
            var uPCCodeParameter = uPCCode != null ?
                new ObjectParameter("UPCCode", uPCCode) :
                new ObjectParameter("UPCCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ScanUPCCode_Result>("SP_ScanUPCCode", uPCCodeParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_RegisterSaleStatus_Result> SP_Rpt_RegisterSaleStatus(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_RegisterSaleStatus_Result>("SP_Rpt_RegisterSaleStatus", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_RegisterSaleStatusByTrans_Result> SP_Rpt_RegisterSaleStatusByTrans(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_RegisterSaleStatusByTrans_Result>("SP_Rpt_RegisterSaleStatusByTrans", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_CashierSaleStatus_Result> SP_Rpt_CashierSaleStatus(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_CashierSaleStatus_Result>("SP_Rpt_CashierSaleStatus", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_Rpt_CashierSaleStatusByTrans_Result> SP_Rpt_CashierSaleStatusByTrans(Nullable<long> sTOREID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sTOREIDParameter = sTOREID.HasValue ?
                new ObjectParameter("STOREID", sTOREID) :
                new ObjectParameter("STOREID", typeof(long));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Rpt_CashierSaleStatusByTrans_Result>("SP_Rpt_CashierSaleStatusByTrans", sTOREIDParameter, fromDateParameter, toDateParameter);
        }
    }
}
