//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExceptionLog
    {
        public long ExceptionID { get; set; }
        public string ExceptionName { get; set; }
        public string Discription { get; set; }
        public string PageName { get; set; }
        public Nullable<long> PageLine { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CounterIP { get; set; }
    }
}
