//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TillStatusReport
    {
        public long TillStatusReportID { get; set; }
        public Nullable<System.DateTime> SelectedDate { get; set; }
        public Nullable<long> CashierID { get; set; }
        public string CashierName { get; set; }
        public Nullable<decimal> Coin { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> CreditCard { get; set; }
        public Nullable<decimal> Checks { get; set; }
        public Nullable<decimal> CashPayout { get; set; }
        public Nullable<decimal> TakeOut { get; set; }
        public Nullable<decimal> BackInDrawer { get; set; }
        public Nullable<decimal> SortBy { get; set; }
        public Nullable<decimal> OverBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<decimal> Lotto { get; set; }
        public Nullable<decimal> SelfService { get; set; }
        public Nullable<decimal> Scrathers { get; set; }
    }
}
