//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductLedger
    {
        public long ProductLedgerID { get; set; }
        public Nullable<long> OrderLineID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> LedgerTypeID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> PostedPurchaseHeaderID { get; set; }
        public Nullable<long> StoreID { get; set; }
        public Nullable<long> TaxGroupCodeID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<long> SectionID { get; set; }
        public Nullable<long> UnitOfMeasureID { get; set; }
        public string UPCCode { get; set; }
        public string QRCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> RemainingQty { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<bool> IsForceTax { get; set; }
        public Nullable<decimal> OverridePrice { get; set; }
    }
}
