//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeMaster
    {
        public long EmployeeID { get; set; }
        public Nullable<long> RoleID { get; set; } 
        public Nullable<long> StoreID { get; set; } 
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<decimal> MaxVoidAmount { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> IsCashPayout { get; set; }
        public Nullable<bool> IsLottoFunction { get; set; }
    }
}
