//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PriceHistory
    {
        public long PriceHistoryID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> CaseQty { get; set; }
        public Nullable<decimal> CasePrice { get; set; }
        public Nullable<decimal> GroupPrice { get; set; }
        public Nullable<decimal> GroupQty { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
