//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UpdateLog
    {
        public long UpdateID { get; set; }
        public string TblName { get; set; }
        public string UpdateType { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<long> CounterID { get; set; }
        public string CounterIP { get; set; }
        public string MacAddress { get; set; }
        public Nullable<bool> IsChange { get; set; }
    }
}
