//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SyncLog
    {
        public long SyncLogID { get; set; }
        public string SyncType { get; set; }
        public Nullable<System.DateTime> SyncDateTime { get; set; }
        public string CounterIP { get; set; }
        public string MacAddress { get; set; }
        public Nullable<long> CounterID { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
