//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceMaster
    {
        public long InvoiceID { get; set; }
        public Nullable<long> PostedPurchaseHeaderID { get; set; }
        public Nullable<long> StoreID { get; set; }
        public Nullable<long> PONumber { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ShippedBy { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Adjustment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDelete { get; set; }
        public bool IsActive { get; set; }
    }
}
