//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerMaster
    {
        public long CustomerID { get; set; }
        public Nullable<long> StoreID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string ZipCode { get; set; }
        public string Message { get; set; }
        public Nullable<bool> NewsLetter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string ResellerID { get; set; }
        public Nullable<bool> TaxExempted { get; set; }
        public string BusinessName { get; set; }
        public string City { get; set; }
    }
}
