//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CounterMaster
    {
        public long CounterID { get; set; }
        public Nullable<long> StoreID { get; set; }
        public Nullable<int> CounterNo { get; set; }
        public string CounterIP { get; set; }
        public Nullable<long> LoginID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string MacAddress { get; set; }
        public string CurrentLoginUser { get; set; }
        public string CurrentVersion { get; set; }
        public Nullable<int> LastReleaseID { get; set; }
        public Nullable<int> CurrentReleaseID { get; set; }
        public Nullable<System.DateTime> ReleaseUpdatedDate { get; set; }
        public Nullable<long> ReleaseUpdatedBy { get; set; }
        public string SystemType { get; set; }
        public Nullable<bool> IsLTSystemActive { get; set; }
    }
}
