//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderEPXLog
    {
        public int EpxId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<long> StoreID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Response { get; set; }
        public string TransactionNo { get; set; }
        public string RequestSend { get; set; }
        public string TVR { get; set; }
        public string CardType { get; set; }
        public string EmvAid { get; set; }
        public string TSI { get; set; }
        public string ResponseValue { get; set; }
    }
}
